#! /usr/bin/env python
#
# sitemap-gen
#
# Copyright (c) 2016 Junpei Kawamoto
#
# This software is released under the MIT License.
#
# http://opensource.org/licenses/mit-license.php
#
"""Generate a sitemap of a website managed in a git repository.
"""
import argparse
from argparse import FileType
import sys
import sitemap_gen


def run(base, root, output):
    """Run `sitemap_gen` command.

    Args:
      base: Base URL of the web site.
      root: Document root of the web site.
      output: Output file object.
    """
    output.write(sitemap_gen.generate(base, root))
    output.write("\n")


def main():
    """The main function.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("base", help="Base URL of the web site.")
    parser.add_argument(
        "--root", default=".",
        help="Document root of the web site. (Default: current dir)")
    parser.add_argument(
        "--output", default=FileType("w")("sitemap.xml"), type=FileType("w"),
        help="Output filename. (Default: sitemap.xml)")

    run(**vars(parser.parse_args()))


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        sys.exit(1)
